# Generated by Django 5.0.6 on 2024-06-13 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_color', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=100)),
                ('numero_garantia', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('detalles_cobertura', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_reparacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_cobertura', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAuto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_combustible', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_transmision', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.color')),
            ],
        ),
        migrations.CreateModel(
            name='AutoGarantia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.garantia')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.marca')),
            ],
            options={
                'unique_together': {('marca', 'nombre_modelo', 'año')},
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.modelo'),
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
            ],
        ),
        migrations.CreateModel(
            name='AutoReparacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_reparacion', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.reparacion')),
            ],
        ),
        migrations.CreateModel(
            name='AutoSeguro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.seguro')),
            ],
        ),
        migrations.CreateModel(
            name='AutoServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateTimeField(auto_now_add=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='tipo_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipoauto'),
        ),
        migrations.AddField(
            model_name='auto',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.tipocombustible'),
        ),
        migrations.AddField(
            model_name='auto',
            name='transmision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.transmision'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.concesionario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.vendedor')),
            ],
        ),
    ]
